In [4]:
import pandas as pd
import numpy as np

In [5]:
mov=pd.read_csv('tmdb_5000_movies.csv')
cred=pd.read_csv('tmdb_5000_credits.csv')

### Data pre-processing:-

In [6]:
mov.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [7]:
cred.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [8]:
cred.head(1)['crew'].values

array(['[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "depart

<p> Merging dataset movies with credits based on "title" as having two dfs is hectic</p>

In [9]:
# merging
movies=mov.merge(cred,on='title')

In [10]:
movies.shape

(4809, 23)

In [11]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [12]:
#content-based recommendation system in process..
#checking out and removing features which wont help us in making "tags" of a film

In [13]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

<p> genres, id(for web), keywords,title,overview,(release_date),cast,crew,

In [14]:
movies=movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [15]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [16]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [17]:
movies.dropna(inplace=True)

In [18]:
movies.duplicated().sum()

np.int64(0)

In [19]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [20]:
#helper func

def convert(obj):
  l=[]
  for i in ast.literal_eval(obj):
    l.append(i['name'])
  return l

In [21]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [22]:
movies['genres']=movies['genres'].apply(convert)

In [23]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [24]:
movies['keywords']=movies['keywords'].apply(convert)

In [25]:
def convert3(obj):
  l=[]
  counter=0
  for i in ast.literal_eval(obj):
    if counter!=3:
      l.append(i['name'])
      counter+=1
    else:
      break
  return l

In [26]:
movies['cast']=movies['cast'].apply(convert3)

In [27]:
def convert_director(obj):
  l=[]
  for i in ast.literal_eval(obj):
    if(i['job']=='Director'):
      l.append(i['name'])
      break
  return l

In [28]:
movies['crew']=movies['crew'].apply(convert_director)

In [29]:
movies.head()

#to show the successful cleaning and pre-processing of data

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [30]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [31]:
#to make string in list form
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [32]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [33]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [34]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [35]:
#make "tag" column

movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [36]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [37]:
new_df=movies[['movie_id','title','tags']]

In [38]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [39]:
#to convert to string back

new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

/tmp/ipykernel_11731/1804035852.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [40]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [41]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [42]:
#everything to lower case
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

/tmp/ipykernel_11731/4029159476.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [43]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

### Vectorization:-

In [44]:
# applying stemming- to avoid similiar words like- accept,accepts, accepted,etc etc like this only
# so they are now counted as one word like all can be brought in the category accept

In [45]:
import nltk

In [46]:
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)

In [47]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [48]:
def stem(text):
  y=[]
  for i in text.split():
    y.append(ps.stem(i))
  return " ".join(y)

In [49]:
new_df['tags']=new_df['tags'].apply(stem)

/tmp/ipykernel_11731/3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [50]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [51]:
from sklearn.feature_extraction.text import CountVectorizer

cv=CountVectorizer(max_features=5000,stop_words='english')

In [52]:
vectors=cv.fit_transform(new_df['tags']).toarray()

In [53]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [54]:
from sklearn.metrics.pairwise import cosine_similarity

In [55]:
s=cosine_similarity(vectors)

In [56]:
cosine_similarity(vectors).shape

(4806, 4806)

In [57]:
s

array([[1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
        0.        ],
       [0.08346223, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
        0.02615329],
       [0.0860309 , 0.06063391, 1.        , ..., 0.02451452, 0.        ,
        0.        ],
       ...,
       [0.04499213, 0.02378257, 0.02451452, ..., 1.        , 0.03962144,
        0.04229549],
       [0.        , 0.        , 0.        , ..., 0.03962144, 1.        ,
        0.08714204],
       [0.        , 0.02615329, 0.        , ..., 0.04229549, 0.08714204,
        1.        ]])

In [58]:
# to find index

new_df[new_df['title']=='Batman Begins'].index[0]

np.int64(119)

In [59]:
list(enumerate(s[0]))

# to keep the indices intact and create list of tupples

[(0, np.float64(1.0000000000000002)),
 (1, np.float64(0.08346223261119858)),
 (2, np.float64(0.08603090020146065)),
 (3, np.float64(0.0734718358370645)),
 (4, np.float64(0.1892994097121204)),
 (5, np.float64(0.10838874619051501)),
 (6, np.float64(0.04024218182927669)),
 (7, np.float64(0.14673479641335554)),
 (8, np.float64(0.05923488777590923)),
 (9, np.float64(0.0978231976089037)),
 (10, np.float64(0.10259783520851541)),
 (11, np.float64(0.09464970485606021)),
 (12, np.float64(0.09037128496931669)),
 (13, np.float64(0.04499212706658476)),
 (14, np.float64(0.12988108336653278)),
 (15, np.float64(0.06282808624375433)),
 (16, np.float64(0.07894736842105264)),
 (17, np.float64(0.13977653617040256)),
 (18, np.float64(0.09493290614465533)),
 (19, np.float64(0.0830812984794528)),
 (20, np.float64(0.058038100008800934)),
 (21, np.float64(0.10968169942141635)),
 (22, np.float64(0.0662266178532522)),
 (23, np.float64(0.08740748201220976)),
 (24, np.float64(0.0533380747062665)),
 (25, np.float64(0.05101627678885769)),
 (26, np.float64(0.15389675281277312)),
 (27, np.float64(0.18693292157876878)),
 (28, np.float64(0.116543309349613)),
 (29, np.float64(0.065033247714309)),
 (30, np.float64(0.06684847767323797)),
 (31, np.float64(0.15907119074394446)),
 (32, np.float64(0.08520286456846099)),
 (33, np.float64(0.09733285267845754)),
 (34, np.float64(0.0)),
 (35, np.float64(0.09933992677987831)),
 (36, np.float64(0.17119059581558146)),
 (37, np.float64(0.07894736842105264)),
 (38, np.float64(0.08111071056538127)),
 (39, np.float64(0.08226127456606226)),
 (40, np.float64(0.07694837640638656)),
 (41, np.float64(0.16563698349810535)),
 (42, np.float64(0.0)),
 (43, np.float64(0.09086217008485092)),
 (44, np.float64(0.03382550457458692)),
 (45, np.float64(0.08240856434303293)),
 (46, np.float64(0.1391037210186643)),
 (47, np.float64(0.19672236884115843)),
 (48, np.float64(0.08447772061910234)),
 (49, np.float64(0.0582716546748065)),
 (50, np.float64(0.11295649894498103)),
 (51, np.float64(0.07987230638308718)),
 (52, np.float64(0.14673479641335554)),
 (53, np.float64(0.042973504259354006)),
 (54, np.float64(0.031219527052723135)),
 (55, np.float64(0.07038153430777869)),
 (56, np.float64(0.13834289277321493)),
 (57, np.float64(0.024182541670333724)),
 (58, np.float64(0.06748819059987714)),
 (59, np.float64(0.07254762501100116)),
 (60, np.float64(0.018367958959266125)),
 (61, np.float64(0.23179316248638276)),
 (62, np.float64(0.0837707816583391)),
 (63, np.float64(0.08175191193132876)),
 (64, np.float64(0.029617443887954616)),
 (65, np.float64(0.019529164171612674)),
 (66, np.float64(0.02249606353329238)),
 (67, np.float64(0.16452254913212452)),
 (68, np.float64(0.1204950466257556)),
 (69, np.float64(0.02649064714130088)),
 (70, np.float64(0.076004188790721)),
 (71, np.float64(0.07336739820667779)),
 (72, np.float64(0.13710212427677043)),
 (73, np.float64(0.0331133089266261)),
 (74, np.float64(0.2024645717996314)),
 (75, np.float64(0.10390486669322622)),
 (76, np.float64(0.07175473098524099)),
 (77, np.float64(0.014394823400711486)),
 (78, np.float64(0.050669459193814)),
 (79, np.float64(0.0623109738595896)),
 (80, np.float64(0.050464733268936676)),
 (81, np.float64(0.11020775375559676)),
 (82, np.float64(0.076004188790721)),
 (83, np.float64(0.17996850826633903)),
 (84, np.float64(0.12361284651454937)),
 (85, np.float64(0.1141270638770543)),
 (86, np.float64(0.07098727864204515)),
 (87, np.float64(0.11128297681493143)),
 (88, np.float64(0.09037128496931669)),
 (89, np.float64(0.05757929360284594)),
 (90, np.float64(0.06131393394849658)),
 (91, np.float64(0.16692446522239718)),
 (92, np.float64(0.0623109738595896)),
 (93, np.float64(0.07098727864204515)),
 (94, np.float64(0.1873171623163388)),
 (95, np.float64(0.14048787173725413)),
 (96, np.float64(0.07694837640638656)),
 (97, np.float64(0.06952346619889824)),
 (98, np.float64(0.07509392614826384)),
 (99, np.float64(0.02666903735313325)),
 (100, np.float64(0.06765100914917384)),
 (101, np.float64(0.07694837640638656)),
 (102, np.float64(0.12462194771917919)),
 (103, np.float64(0.07987230638308718)),
 (104, np.float64(0.05564148840746572)),
 (105, np.float64(0.1037571695799112)),
 (106, np.float64(0.0623109738595896)),
 (107, np.float64(0.061806423257274694)),
 (108, np.float64(0.14509525002200235)),
 (109, np.float64(0.06488856845230502)),
 (110, np.float64(0.04499212706658476)),
 (111, np.float64(0.15018785229652767)),
 (112, np.float64(0.07694837640638656)),
 (113, np.float64(0.043355498476206004)),
 (114, np.float64(0.04588314677411236)),
 (115, np.float64(0.043747863925980714)),
 (116, np.float64(0.04783648732349399)),
 (117, np.float64(0.05923488777590923)),
 (118, np.float64(0.03364315551262445)),
 (119, np.float64(0.043355498476206004)),
 (120, np.float64(0.0)),
 (121, np.float64(0.11128297681493143)),
 (122, np.float64(0.116543309349613)),
 (123, np.float64(0.1124803176664619)),
 (124, np.float64(0.06748819059987714)),
 (125, np.float64(0.07843304784240032)),
 (126, np.float64(0.13334518676566626)),
 (127, np.float64(0.14601068654819693)),
 (128, np.float64(0.0)),
 (129, np.float64(0.09269795493186431)),
 (130, np.float64(0.027036903521793755)),
 (131, np.float64(0.10526315789473685)),
 (132, np.float64(0.04499212706658476)),
 (133, np.float64(0.028239124736245257)),
 (134, np.float64(0.12977713690461004)),
 (135, np.float64(0.0)),
 (136, np.float64(0.023414645289542353)),
 (137, np.float64(0.0301237616564389)),
 (138, np.float64(0.12824729401064427)),
 (139, np.float64(0.12072654548783007)),
 (140, np.float64(0.04499212706658476)),
 (141, np.float64(0.08740748201220976)),
 (142, np.float64(0.08471737420873576)),
 (143, np.float64(0.08671099695241201)),
 (144, np.float64(0.05006261743217589)),
 (145, np.float64(0.019252140716412975)),
 (146, np.float64(0.016222142113076255)),
 (147, np.float64(0.05564148840746572)),
 (148, np.float64(0.09733285267845754)),
 (149, np.float64(0.15511334686589626)),
 (150, np.float64(0.16426202236672155)),
 (151, np.float64(0.2029530274475215)),
 (152, np.float64(0.08346223261119858)),
 (153, np.float64(0.07868894753646337)),
 (154, np.float64(0.06131393394849658)),
 (155, np.float64(0.02043797798283219)),
 (156, np.float64(0.05990422978731538)),
 (157, np.float64(0.09933992677987831)),
 (158, np.float64(0.13369695534647594)),
 (159, np.float64(0.06362847629757779)),
 (160, np.float64(0.11712303424679457)),
 (161, np.float64(0.03181423814878889)),
 (162, np.float64(0.0331133089266261)),
 (163, np.float64(0.051298917604257706)),
 (164, np.float64(0.08000711205939975)),
 (165, np.float64(0.04588314677411236)),
 (166, np.float64(0.12515654358043973)),
 (167, np.float64(0.09037128496931669)),
 (168, np.float64(0.17521916101261562)),
 (169, np.float64(0.08830215713766959)),
 (170, np.float64(0.10650358071057624)),
 (171, np.float64(0.02271554252121273)),
 (172, np.float64(0.21239769762143662)),
 (173, np.float64(0.023174488732966077)),
 (174, np.float64(0.07792865001991967)),
 (175, np.float64(0.07098727864204515)),
 (176, np.float64(0.02913582733740325)),
 (177, np.float64(0.0)),
 (178, np.float64(0.024455799402225926)),
 (179, np.float64(0.07254762501100116)),
 (180, np.float64(0.022075539284417398)),
 (181, np.float64(0.04499212706658476)),
 (182, np.float64(0.11707322644771176)),
 (183, np.float64(0.07038153430777869)),
 (184, np.float64(0.17521916101261562)),
 (185, np.float64(0.050669459193814)),
 (186, np.float64(0.05901671065234752)),
 (187, np.float64(0.15389675281277312)),
 (188, np.float64(0.022075539284417398)),
 (189, np.float64(0.1147078669352809)),
 (190, np.float64(0.08447772061910234)),
 (191, np.float64(0.04891159880445185)),
 (192, np.float64(0.047324852428030105)),
 (193, np.float64(0.07878168645790681)),
 (194, np.float64(0.0)),
 (195, np.float64(0.05923488777590923)),
 (196, np.float64(0.05195243334661311)),
 (197, np.float64(0.036973693332326786)),
 (198, np.float64(0.057353933467640436)),
 (199, np.float64(0.08671099695241201)),
 (200, np.float64(0.10882143751650175)),
 (201, np.float64(0.0)),
 (202, np.float64(0.03181423814878889)),
 (203, np.float64(0.08346223261119858)),
 (204, np.float64(0.04947706959952935)),
 (205, np.float64(0.07443229275647868)),
 (206, np.float64(0.11092107999698035)),
 (207, np.float64(0.07694837640638656)),
 (208, np.float64(0.12262786789699316)),
 (209, np.float64(0.06765100914917384)),
 (210, np.float64(0.07509392614826384)),
 (211, np.float64(0.024455799402225926)),
 (212, np.float64(0.06622661785325219)),
 (213, np.float64(0.05901671065234752)),
 (214, np.float64(0.0)),
 (215, np.float64(0.06622661785325219)),
 (216, np.float64(0.06488856845230502)),
 (217, np.float64(0.08520286456846099)),
 (218, np.float64(0.03823595564509363)),
 (219, np.float64(0.09197090092274487)),
 (220, np.float64(0.1777046633277277)),
 (221, np.float64(0.047324852428030105)),
 (222, np.float64(0.07987230638308718)),
 (223, np.float64(0.10390486669322622)),
 (224, np.float64(0.060833032924035954)),
 (225, np.float64(0.046829290579084706)),
 (226, np.float64(0.0301237616564389)),
 (227, np.float64(0.08226127456606226)),
 (228, np.float64(0.11037769642208699)),
 (229, np.float64(0.1074861545850028)),
 (230, np.float64(0.09183979479633063)),
 (231, np.float64(0.0)),
 (232, np.float64(0.11128297681493143)),
 (233, np.float64(0.1037571695799112)),
 (234, np.float64(0.08594700851870801)),
 (235, np.float64(0.076004188790721)),
 (236, np.float64(0.11470786693528087)),
 (237, np.float64(0.0662266178532522)),
 (238, np.float64(0.11092107999698035)),
 (239, np.float64(0.09125667909262308)),
 (240, np.float64(0.046829290579084706)),
 (241, np.float64(0.07894736842105264)),
 (242, np.float64(0.08111071056538127)),
 (243, np.float64(0.09269795493186431)),
 (244, np.float64(0.09197090092274487)),
 (245, np.float64(0.08111071056538127)),
 (246, np.float64(0.07647191129018727)),
 (247, np.float64(0.0)),
 (248, np.float64(0.04456565178215865)),
 (249, np.float64(0.13834289277321493)),
 (250, np.float64(0.0)),
 (251, np.float64(0.04188539082916955)),
 (252, np.float64(0.020277677641345318)),
 (253, np.float64(0.06335829046432676)),
 (254, np.float64(0.06952346619889824)),
 (255, np.float64(0.0)),
 (256, np.float64(0.11164843913471803)),
 (257, np.float64(0.0533380747062665)),
 (258, np.float64(0.01769980813511972)),
 (259, np.float64(0.06131393394849658)),
 (260, np.float64(0.20395079136182276)),
 (261, np.float64(0.024182541670333724)),
 (262, np.float64(0.10650358071057624)),
 (263, np.float64(0.09733285267845754)),
 (264, np.float64(0.0)),
 (265, np.float64(0.02742042485535409)),
 (266, np.float64(0.0989541391990587)),
 (267, np.float64(0.06488856845230502)),
 (268, np.float64(0.052631578947368425)),
 (269, np.float64(0.029617443887954616)),
 (270, np.float64(0.08830215713766959)),
 (271, np.float64(0.07098727864204515)),
 (272, np.float64(0.02782074420373286)),
 (273, np.float64(0.021119430154775586)),
 (274, np.float64(0.08977310580745099)),
 (275, np.float64(0.1433848336691011)),
 (276, np.float64(0.06243905410544627)),
 (277, np.float64(0.053099424405359155)),
 (278, np.float64(0.11707322644771176)),
 (279, np.float64(0.09269795493186431)),
 (280, np.float64(0.0)),
 (281, np.float64(0.065033247714309)),
 (282, np.float64(0.04456565178215865)),
 (283, np.float64(0.02742042485535409)),
 (284, np.float64(0.018367958959266125)),
 (285, np.float64(0.019529164171612674)),
 (286, np.float64(0.0781166566864507)),
 (287, np.float64(0.025976216673306556)),
 (288, np.float64(0.02742042485535409)),
 (289, np.float64(0.04588314677411236)),
 (290, np.float64(0.06243905410544627)),
 (291, np.float64(0.04947706959952935)),
 (292, np.float64(0.08885233166386385)),
 (293, np.float64(0.029617443887954616)),
 (294, np.float64(0.1433848336691011)),
 (295, np.float64(0.10526315789473685)),
 (296, np.float64(0.038778336716474064)),
 (297, np.float64(0.044151078568834795)),
 (298, np.float64(0.0)),
 (299, np.float64(0.05945550264670635)),
 (300, np.float64(0.1711905958155815)),
 (301, np.float64(0.09365858115816939)),
 (302, np.float64(0.07024393586862707)),
 (303, np.float64(0.028239124736245257)),
 (304, np.float64(0.06578947368421054)),
 (305, np.float64(0.19007487139298027)),
 (306, np.float64(0.08111071056538127)),
 (307, np.float64(0.10876595882948199)),
 (308, np.float64(0.06765100914917384)),
 (309, np.float64(0.06243905410544627)),
 (310, np.float64(0.03065696697424829)),
 (311, np.float64(0.15018785229652765)),
 (312, np.float64(0.10012523486435178)),
 (313, np.float64(0.05484084971070818)),
 (314, np.float64(0.0)),
 (315, np.float64(0.08346223261119858)),
 (316, np.float64(0.0)),
 (317, np.float64(0.0)),
 (318, np.float64(0.0)),
 (319, np.float64(0.09933992677987831)),
 (320, np.float64(0.03065696697424829)),
 (321, np.float64(0.0)),
 (322, np.float64(0.2105263157894737)),
 (323, np.float64(0.029617443887954616)),
 (324, np.float64(0.024182541670333724)),
 (325, np.float64(0.09933992677987831)),
 (326, np.float64(0.05647824947249051)),
 (327, np.float64(0.027036903521793755)),
 (328, np.float64(0.02742042485535409)),
 (329, np.float64(0.07894736842105264)),
 (330, np.float64(0.10012523486435178)),
 (331, np.float64(0.08998425413316952)),
 (332, np.float64(0.106676149412533)),
 (333, np.float64(0.024455799402225926)),
 (334, np.float64(0.0967301666813349)),
 (335, np.float64(0.046348977465932154)),
 (336, np.float64(0.06917144638660747)),
 (337, np.float64(0.04543108504242546)),
 (338, np.float64(0.0)),
 (339, np.float64(0.04891159880445185)),
 (340, np.float64(0.04947706959952935)),
 (341, np.float64(0.08226127456606226)),
 (342, np.float64(0.16122923187750418)),
 (343, np.float64(0.019252140716412975)),
 (344, np.float64(0.029617443887954616)),
 (345, np.float64(0.023174488732966077)),
 (346, np.float64(0.0)),
 (347, np.float64(0.0)),
 (348, np.float64(0.06131393394849658)),
 (349, np.float64(0.076004188790721)),
 (350, np.float64(0.04891159880445185)),
 (351, np.float64(0.0)),
 (352, np.float64(0.02742042485535409)),
 (353, np.float64(0.04120428217151646)),
 (354, np.float64(0.021677749238103002)),
 (355, np.float64(0.03650267163704923)),
 (356, np.float64(0.09037128496931669)),
 (357, np.float64(0.0)),
 (358, np.float64(0.0602475233128778)),
 (359, np.float64(0.031219527052723135)),
 (360, np.float64(0.020942695414584774)),
 (361, np.float64(0.07509392614826384)),
 (362, np.float64(0.09544271444636668)),
 (363, np.float64(0.09909250441117726)),
 (364, np.float64(0.023414645289542353)),
 (365, np.float64(0.07509392614826384)),
 (366, np.float64(0.05647824947249051)),
 (367, np.float64(0.0)),
 (368, np.float64(0.12977713690461004)),
 (369, np.float64(0.126673647984535)),
 (370, np.float64(0.050669459193814)),
 (371, np.float64(0.09567297464698798)),
 (372, np.float64(0.047324852428030105)),
 (373, np.float64(0.17292861596651865)),
 (374, np.float64(0.03797316245786213)),
 (375, np.float64(0.061313933948496574)),
 (376, np.float64(0.046829290579084706)),
 (377, np.float64(0.0)),
 (378, np.float64(0.0)),
 (379, np.float64(0.05073825686188038)),
 (380, np.float64(0.05195243334661311)),
 (381, np.float64(0.0837707816583391)),
 (382, np.float64(0.0)),
 (383, np.float64(0.043355498476206004)),
 (384, np.float64(0.028676966733820218)),
 (385, np.float64(0.0)),
 (386, np.float64(0.021873931962990357)),
 (387, np.float64(0.023662426214015053)),
 (388, np.float64(0.0)),
 (389, np.float64(0.08740748201220976)),
 (390, np.float64(0.026315789473684213)),
 (391, np.float64(0.056573571480353566)),
 (392, np.float64(0.0301237616564389)),
 (393, np.float64(0.0)),
 (394, np.float64(0.024738534799764674)),
 (395, np.float64(0.05195243334661311)),
 (396, np.float64(0.043747863925980714)),
 (397, np.float64(0.05195243334661311)),
 (398, np.float64(0.0)),
 (399, np.float64(0.023662426214015053)),
 (400, np.float64(0.09037128496931669)),
 (401, np.float64(0.03065696697424829)),
 (402, np.float64(0.08226127456606226)),
 (403, np.float64(0.0830812984794528)),
 (404, np.float64(0.06243905410544627)),
 (405, np.float64(0.05564148840746572)),
 (406, np.float64(0.0207703246198632)),
 (407, np.float64(0.021300716142115247)),
 (408, np.float64(0.03244428422615251)),
 (409, np.float64(0.0)),
 (410, np.float64(0.0978231976089037)),
 (411, np.float64(0.0533380747062665)),
 (412, np.float64(0.09567297464698798)),
 (413, np.float64(0.1411956236812263)),
 (414, np.float64(0.029617443887954616)),
 (415, np.float64(0.053418342734682205)),
 (416, np.float64(0.050669459193814)),
 (417, np.float64(0.03244428422615251)),
 (418, np.float64(0.03539961627023944)),
 (419, np.float64(0.06882472016116853)),
 (420, np.float64(0.1124803176664619)),
 (421, np.float64(0.023174488732966077)),
 (422, np.float64(0.116543309349613)),
 (423, np.float64(0.04120428217151646)),
 (424, np.float64(0.036973693332326786)),
 (425, np.float64(0.06390214842634574)),
 (426, np.float64(0.05374307729250139)),
 (427, np.float64(0.026315789473684213)),
 (428, np.float64(0.055824219567359015)),
 (429, np.float64(0.0)),
 (430, np.float64(0.050669459193814)),
 (431, np.float64(0.024182541670333724)),
 (432, np.float64(0.11357771260606365)),
 (433, np.float64(0.031219527052723135)),
 (434, np.float64(0.0)),
 (435, np.float64(0.03539961627023944)),
 (436, np.float64(0.0)),
 (437, np.float64(0.025649458802128853)),
 (438, np.float64(0.12227899701112963)),
 (439, np.float64(0.026315789473684213)),
 (440, np.float64(0.024738534799764674)),
 (441, np.float64(0.057353933467640436)),
 (442, np.float64(0.04543108504242546)),
 (443, np.float64(0.06390214842634574)),
 (444, np.float64(0.0)),
 (445, np.float64(0.0989541391990587)),
 (446, np.float64(0.023174488732966077)),
 (447, np.float64(0.06446025638903101)),
 (448, np.float64(0.021300716142115247)),
 (449, np.float64(0.10968169942141635)),
 (450, np.float64(0.021300716142115247)),
 (451, np.float64(0.025031308716087945)),
 (452, np.float64(0.03065696697424829)),
 (453, np.float64(0.024455799402225926)),
 (454, np.float64(0.11587244366483038)),
 (455, np.float64(0.060833032924035954)),
 (456, np.float64(0.043355498476206004)),
 (457, np.float64(0.08603090020146065)),
 (458, np.float64(0.043355498476206004)),
 (459, np.float64(0.03458572319330373)),
 (460, np.float64(0.024182541670333724)),
 (461, np.float64(0.1411956236812263)),
 (462, np.float64(0.032283269414765066)),
 (463, np.float64(0.03244428422615251)),
 (464, np.float64(0.0)),
 (465, np.float64(0.0)),
 (466, np.float64(0.14509525002200233)),
 (467, np.float64(0.10559715077387793)),
 (468, np.float64(0.02782074420373286)),
 (469, np.float64(0.05945550264670635)),
 (470, np.float64(0.04543108504242546)),
 (471, np.float64(0.06390214842634574)),
 (472, np.float64(0.106676149412533)),
 (473, np.float64(0.09269795493186431)),
 (474, np.float64(0.0)),
 (475, np.float64(0.043747863925980714)),
 (476, np.float64(0.13530201829834768)),
 (477, np.float64(0.0)),
 (478, np.float64(0.05407380704358751)),
 (479, np.float64(0.08797691788472335)),
 (480, np.float64(0.0978231976089037)),
 (481, np.float64(0.0)),
 (482, np.float64(0.021873931962990357)),
 (483, np.float64(0.12487810821089254)),
 (484, np.float64(0.02913582733740325)),
 (485, np.float64(0.052631578947368425)),
 (486, np.float64(0.07992075789278003)),
 (487, np.float64(0.12725695259515557)),
 (488, np.float64(0.06657426652986062)),
 (489, np.float64(0.0)),
 (490, np.float64(0.14159846508095775)),
 (491, np.float64(0.09909250441117726)),
 (492, np.float64(0.076004188790721)),
 (493, np.float64(0.03065696697424829)),
 (494, np.float64(0.0)),
 (495, np.float64(0.19088542889273336)),
 (496, np.float64(0.0)),
 (497, np.float64(0.0)),
 (498, np.float64(0.06765100914917384)),
 (499, np.float64(0.0)),
 (500, np.float64(0.025976216673306556)),
 (501, np.float64(0.08175191193132876)),
 (502, np.float64(0.13369695534647594)),
 (503, np.float64(0.07509392614826384)),
 (504, np.float64(0.0)),
 (505, np.float64(0.13530201829834768)),
 (506, np.float64(0.03458572319330373)),
 (507, np.float64(0.255608593705383)),
 (508, np.float64(0.10259783520851541)),

In [60]:
sorted(list(enumerate(s[0])),reverse=True,key=lambda x:x[1])
# sorted on the basis of 2nd col

[(0, np.float64(1.0000000000000002)),
 (1214, np.float64(0.28676966733820225)),
 (2405, np.float64(0.26901379342448517)),
 (3728, np.float64(0.2605130246476754)),
 (507, np.float64(0.255608593705383)),
 (539, np.float64(0.25038669783359574)),
 (582, np.float64(0.24511108480187255)),
 (1202, np.float64(0.24455799402225922)),
 (1192, np.float64(0.2367785320221084)),
 (61, np.float64(0.23179316248638276)),
 (778, np.float64(0.23174488732966075)),
 (4046, np.float64(0.2278389747471728)),
 (1916, np.float64(0.2252817784447915)),
 (2782, np.float64(0.21853668936906193)),
 (172, np.float64(0.21239769762143662)),
 (972, np.float64(0.2108663315950723)),
 (322, np.float64(0.2105263157894737)),
 (2329, np.float64(0.20443988269091456)),
 (3606, np.float64(0.20437977982832192)),
 (260, np.float64(0.20395079136182276)),
 (151, np.float64(0.2029530274475215)),
 (4190, np.float64(0.2029530274475215)),
 (1440, np.float64(0.20277677641345318)),
 (74, np.float64(0.2024645717996314)),
 (1087, np.float64(0.2020475485519274)),
 (3671, np.float64(0.1979082783981174)),
 (973, np.float64(0.19767387315371682)),
 (577, np.float64(0.1976738731537168)),
 (47, np.float64(0.19672236884115843)),
 (2969, np.float64(0.19252140716412977)),
 (942, np.float64(0.19134594929397597)),
 (495, np.float64(0.19088542889273336)),
 (1199, np.float64(0.19088542889273336)),
 (305, np.float64(0.19007487139298027)),
 (4, np.float64(0.1892994097121204)),
 (4405, np.float64(0.18731716231633883)),
 (94, np.float64(0.1873171623163388)),
 (27, np.float64(0.18693292157876878)),
 (3325, np.float64(0.1860807318911967)),
 (1273, np.float64(0.18394180184548975)),
 (1327, np.float64(0.18394180184548975)),
 (2997, np.float64(0.1813690625275029)),
 (3997, np.float64(0.18074256993863339)),
 (83, np.float64(0.17996850826633903)),
 (1069, np.float64(0.17954621161490197)),
 (220, np.float64(0.1777046633277277)),
 (1319, np.float64(0.17699808135119718)),
 (168, np.float64(0.17521916101261562)),
 (184, np.float64(0.17521916101261562)),
 (2200, np.float64(0.17521916101261562)),
 (4336, np.float64(0.17521916101261562)),
 (931, np.float64(0.1748149640244195)),
 (373, np.float64(0.17292861596651865)),
 (300, np.float64(0.1711905958155815)),
 (3536, np.float64(0.1711905958155815)),
 (36, np.float64(0.17119059581558146)),
 (3160, np.float64(0.17040572913692198)),
 (1978, np.float64(0.16943474841747155)),
 (529, np.float64(0.16742770563222897)),
 (1827, np.float64(0.16742770563222897)),
 (91, np.float64(0.16692446522239718)),
 (661, np.float64(0.1661625969589056)),
 (41, np.float64(0.16563698349810535)),
 (67, np.float64(0.16452254913212452)),
 (150, np.float64(0.16426202236672155)),
 (1533, np.float64(0.16222142113076254)),
 (2511, np.float64(0.16222142113076254)),
 (342, np.float64(0.16122923187750418)),
 (595, np.float64(0.16059101370939324)),
 (31, np.float64(0.15907119074394446)),
 (1176, np.float64(0.15789473684210528)),
 (4008, np.float64(0.15737789507292674)),
 (2727, np.float64(0.15609763526361567)),
 (149, np.float64(0.15511334686589626)),
 (838, np.float64(0.1540171257313038)),
 (26, np.float64(0.15389675281277312)),
 (187, np.float64(0.15389675281277312)),
 (1379, np.float64(0.152008377581442)),
 (111, np.float64(0.15018785229652767)),
 (1342, np.float64(0.15018785229652767)),
 (311, np.float64(0.15018785229652765)),
 (513, np.float64(0.14843120879858804)),
 (2071, np.float64(0.14808721943977307)),
 (7, np.float64(0.14673479641335554)),
 (52, np.float64(0.14673479641335554)),
 (2756, np.float64(0.14659886790209342)),
 (127, np.float64(0.14601068654819693)),
 (579, np.float64(0.14567913668701626)),
 (581, np.float64(0.14567913668701626)),
 (108, np.float64(0.14509525002200235)),
 (1295, np.float64(0.14509525002200235)),
 (466, np.float64(0.14509525002200233)),
 (1392, np.float64(0.14421498760030763)),
 (1475, np.float64(0.1442149876003076)),
 (1353, np.float64(0.14350946197048198)),
 (1934, np.float64(0.14350946197048198)),
 (275, np.float64(0.1433848336691011)),
 (294, np.float64(0.1433848336691011)),
 (3352, np.float64(0.1433848336691011)),
 (1054, np.float64(0.1419745572840903)),
 (1271, np.float64(0.1419745572840903)),
 (490, np.float64(0.14159846508095775)),
 (1484, np.float64(0.14159846508095775)),
 (413, np.float64(0.1411956236812263)),
 (461, np.float64(0.1411956236812263)),
 (568, np.float64(0.1411956236812263)),
 (2492, np.float64(0.1411956236812263)),
 (95, np.float64(0.14048787173725413)),
 (17, np.float64(0.13977653617040256)),
 (46, np.float64(0.1391037210186643)),
 (3407, np.float64(0.1391037210186643)),
 (1961, np.float64(0.13872950617564817)),
 (56, np.float64(0.13834289277321493)),
 (249, np.float64(0.13834289277321493)),
 (1325, np.float64(0.13834289277321493)),
 (3779, np.float64(0.13834289277321493)),
 (72, np.float64(0.13710212427677043)),
 (859, np.float64(0.13710212427677043)),
 (2165, np.float64(0.13710212427677043)),
 (4538, np.float64(0.13629325512727639)),
 (476, np.float64(0.13530201829834768)),
 (505, np.float64(0.13530201829834768)),
 (668, np.float64(0.13530201829834768)),
 (935, np.float64(0.13530201829834768)),
 (3980, np.float64(0.13530201829834768)),
 (843, np.float64(0.13518451760896877)),
 (1804, np.float64(0.13518451760896877)),
 (4348, np.float64(0.13497638119975428)),
 (1320, np.float64(0.13476498501489081)),
 (158, np.float64(0.13369695534647594)),
 (502, np.float64(0.13369695534647594)),
 (777, np.float64(0.13369695534647594)),
 (126, np.float64(0.13334518676566626)),
 (1556, np.float64(0.13334518676566626)),
 (1369, np.float64(0.1324532357065044)),
 (2374, np.float64(0.1324532357065044)),
 (2580, np.float64(0.1324532357065044)),
 (589, np.float64(0.13245323570650439)),
 (4077, np.float64(0.13157894736842107)),
 (2129, np.float64(0.13124359177794215)),
 (14, np.float64(0.12988108336653278)),
 (1013, np.float64(0.12988108336653278)),
 (2177, np.float64(0.12988108336653278)),
 (3620, np.float64(0.12988108336653278)),
 (134, np.float64(0.12977713690461004)),
 (368, np.float64(0.12977713690461004)),
 (1770, np.float64(0.12977713690461004)),
 (2869, np.float64(0.12892051277806202)),
 (138, np.float64(0.12824729401064427)),
 (1084, np.float64(0.12824729401064427)),
 (2682, np.float64(0.12824729401064427)),
 (4228, np.float64(0.12824729401064427)),
 (487, np.float64(0.12725695259515557)),
 (773, np.float64(0.12725695259515557)),
 (2968, np.float64(0.12725695259515557)),
 (369, np.float64(0.126673647984535)),
 (937, np.float64(0.126673647984535)),
 (1737, np.float64(0.12565617248750865)),
 (2476, np.float64(0.12565617248750865)),
 (166, np.float64(0.12515654358043973)),
 (754, np.float64(0.12515654358043973)),
 (2446, np.float64(0.12515654358043973)),
 (3626, np.float64(0.12515654358043973)),
 (483, np.float64(0.12487810821089254)),
 (1094, np.float64(0.12487810821089254)),
 (1156, np.float64(0.12487810821089254)),
 (102, np.float64(0.12462194771917919)),
 (84, np.float64(0.12361284651454937)),
 (208, np.float64(0.12262786789699316)),
 (2648, np.float64(0.12262786789699316)),
 (3374, np.float64(0.12262786789699316)),
 (1874, np.float64(0.12262786789699313)),
 (438, np.float64(0.12227899701112963)),
 (557, np.float64(0.12227899701112963)),
 (1297, np.float64(0.12227899701112963)),
 (2327, np.float64(0.12166606584807191)),
 (2670, np.float64(0.12166606584807191)),
 (3081, np.float64(0.12166606584807191)),
 (3998, np.float64(0.12166606584807191)),
 (139, np.float64(0.12072654548783007)),
 (68, np.float64(0.1204950466257556)),
 (781, np.float64(0.1204950466257556)),
 (1002, np.float64(0.1204950466257556)),
 (1272, np.float64(0.1204950466257556)),
 (1654, np.float64(0.1204950466257556)),
 (2737, np.float64(0.1204950466257556)),
 (1000, np.float64(0.11980845957463077)),
 (549, np.float64(0.11959121830873498)),
 (870, np.float64(0.11959121830873498)),
 (900, np.float64(0.11959121830873498)),
 (3233, np.float64(0.11959121830873498)),
 (1045, np.float64(0.11846977555181847)),
 (1829, np.float64(0.11846977555181847)),
 (2056, np.float64(0.11846977555181847)),
 (4673, np.float64(0.11846977555181847)),
 (3719, np.float64(0.11803342130469506)),
 (1669, np.float64(0.11803342130469505)),
 (1711, np.float64(0.11803342130469505)),
 (2785, np.float64(0.11803342130469505)),
 (160, np.float64(0.11712303424679457)),
 (182, np.float64(0.11707322644771176)),
 (278, np.float64(0.11707322644771176)),
 (1613, np.float64(0.11707322644771176)),
 (2280, np.float64(0.11707322644771176)),
 (28, np.float64(0.116543309349613)),
 (122, np.float64(0.116543309349613)),
 (422, np.float64(0.116543309349613)),
 (678, np.float64(0.116543309349613)),
 (454, np.float64(0.11587244366483038)),
 (2543, np.float64(0.11587244366483038)),
 (1493, np.float64(0.11551284429847784)),
 (3210, np.float64(0.11506355109724453)),
 (189, np.float64(0.1147078669352809)),
 (1218, np.float64(0.1147078669352809)),
 (236, np.float64(0.11470786693528087)),
 (1299, np.float64(0.11470786693528087)),
 (85, np.float64(0.1141270638770543)),
 (432, np.float64(0.11357771260606365)),
 (1414, np.float64(0.11357771260606365)),
 (889, np.float64(0.11299144295167773)),
 (50, np.float64(0.11295649894498103)),
 (1612, np.float64(0.11295649894498103)),
 (123, np.float64(0.1124803176664619)),
 (420, np.float64(0.1124803176664619)),
 (536, np.float64(0.1124803176664619)),
 (3145, np.float64(0.11239029738980327)),
 (256, np.float64(0.11164843913471803)),
 (808, np.float64(0.11164843913471803)),
 (1346, np.float64(0.11164843913471803)),
 (1571, np.float64(0.11164843913471803)),
 (2368, np.float64(0.11141412945539662)),
 (3307, np.float64(0.11141412945539662)),
 (1508, np.float64(0.11141412945539661)),
 (87, np.float64(0.11128297681493143)),
 (121, np.float64(0.11128297681493143)),
 (232, np.float64(0.11128297681493143)),
 (4468, np.float64(0.11128297681493143)),
 (206, np.float64(0.11092107999698035)),
 (238, np.float64(0.11092107999698035)),
 (228, np.float64(0.11037769642208699)),
 (81, np.float64(0.11020775375559676)),
 (1570, np.float64(0.11020775375559674)),
 (3426, np.float64(0.10968169942141637)),
 (21, np.float64(0.10968169942141635)),
 (449, np.float64(0.10968169942141635)),
 (1029, np.float64(0.10968169942141635)),
 (1941, np.float64(0.10968169942141635)),
 (3006, np.float64(0.10968169942141635)),
 (692, np.float64(0.10936965981495178)),
 (200, np.float64(0.10882143751650175)),
 (627, np.float64(0.10882143751650175)),
 (653, np.float64(0.10882143751650175)),
 (1520, np.float64(0.10882143751650175)),
 (307, np.float64(0.10876595882948199)),
 (5, np.float64(0.10838874619051501)),
 (3091, np.float64(0.10838874619051501)),
 (3628, np.float64(0.10838874619051501)),
 (740, np.float64(0.108388746190515)),
 (786, np.float64(0.10814761408717502)),
 (3496, np.float64(0.10814761408717502)),
 (4777, np.float64(0.10814761408717502)),
 (229, np.float64(0.1074861545850028)),
 (939, np.float64(0.1074861545850028)),
 (572, np.float64(0.10743376064838502)),
 (332, np.float64(0.106676149412533)),
 (472, np.float64(0.106676149412533)),
 (687, np.float64(0.106676149412533)),
 (1235, np.float64(0.106676149412533)),
 (170, np.float64(0.10650358071057624)),
 (262, np.float64(0.10650358071057624)),
 (1164, np.float64(0.10619884881071831)),
 (1497, np.float64(0.10619884881071831)),
 (1741, np.float64(0.10619884881071831)),
 (2157, np.float64(0.10619884881071831)),
 (2517, np.float64(0.10619884881071831)),
 (2630, np.float64(0.10619884881071831)),
 (4133, np.float64(0.10619884881071831)),
 (467, np.float64(0.10559715077387793)),
 (541, np.float64(0.10559715077387793)),
 (1492, np.float64(0.10559715077387793)),
 (131, np.float64(0.10526315789473685)),
 (295, np.float64(0.10526315789473685)),
 (814, np.float64(0.10526315789473685)),
 (2068, np.float64(0.10526315789473685)),
 (3338, np.float64(0.10526315789473685)),
 (2494, np.float64(0.10471347707292386)),
 (75, np.float64(0.10390486669322622)),
 (223, np.float64(0.10390486669322622)),
 (1193, np.float64(0.10390486669322622)),
 (1767, np.float64(0.10390486669322622)),
 (2144, np.float64(0.10390486669322622)),
 (2813, np.float64(0.10390486669322622)),
 (654, np.float64(0.10385162309931599)),
 (2435, np.float64(0.10385162309931599)),
 (105, np.float64(0.1037571695799112)),
 (233, np.float64(0.1037571695799112)),
 (2319, np.float64(0.1037571695799112)),
 (2452, np.float64(0.1037571695799112)),
 (3053, np.float64(0.1037571695799112)),
 (3619, np.float64(0.1037571695799112)),
 (3837, np.float64(0.1037571695799112)),
 (1451, np.float64(0.10301070542879115)),
 (10, np.float64(0.10259783520851541)),
 (508, np.float64(0.10259783520851541)),
 (1080, np.float64(0.10259783520851541)),
 (3150, np.float64(0.10259783520851541)),
 (3632, np.float64(0.10259783520851541)),
 (3753, np.float64(0.10259783520851541)),
 (3872, np.float64(0.10259783520851541)),
 (4095, np.float64(0.10259783520851541)),
 (2102, np.float64(0.10218988991416095)),
 (624, np.float64(0.10147651372376076)),
 (2758, np.float64(0.10147651372376076)),
 (3659, np.float64(0.10147651372376076)),
 (3952, np.float64(0.10147651372376076)),
 (3439, np.float64(0.10138838820672659)),
 (1292, np.float64(0.101338918387628)),
 (2243, np.float64(0.10133891838762799)),
 (1401, np.float64(0.10060545457319173)),
 (1435, np.float64(0.10060545457319173)),
 (2095, np.float64(0.10060545457319173)),
 (312, np.float64(0.10012523486435178)),
 (330, np.float64(0.10012523486435178)),
 (643, np.float64(0.10012523486435178)),
 (986, np.float64(0.10012523486435178)),
 (1035, np.float64(0.10012523486435178)),
 (1610, np.float64(0.10012523486435178)),
 (35, np.float64(0.09933992677987831)),
 (157, np.float64(0.09933992677987831)),
 (319, np.float64(0.09933992677987831)),
 (325, np.float64(0.09933992677987831)),
 (715, np.float64(0.09933992677987831)),
 (1075, np.float64(0.09933992677987831)),
 (1278, np.float64(0.09933992677987831)),
 (1880, np.float64(0.09933992677987831)),
 (2049, np.float64(0.09933992677987831)),
 (4016, np.float64(0.09933992677987831)),
 (4196, np.float64(0.09933992677987831)),
 (4490, np.float64(0.09933992677987831)),
 (363, np.float64(0.09909250441117726)),
 (491, np.float64(0.09909250441117726)),
 (266, np.float64(0.0989541391990587)),
 (445, np.float64(0.0989541391990587)),
 (510, np.float64(0.0989541391990587)),
 (898, np.float64(0.0989541391990587)),
 (3618, np.float64(0.0989541391990587)),
 (3781, np.float64(0.0989541391990587)),
 (3933, np.float64(0.0989541391990587)),
 (1771, np.float64(0.09836118442057921)),
 (9, np.float64(0.0978231976089037)),
 (410, np.float64(0.0978231976089037)),
 (480, np.float64(0.0978231976089037)),
 (535, np.float64(0.0978231976089037)),
 (1107, np.float64(0.0978231976089037)),
 (1397, np.float64(0.0978231976089037)),
 (1819, np.float64(0.0978231976089037)),
 (2249, np.float64(0.0978231976089037)),
 (33, np.float64(0.09733285267845754)),
 (148, np.float64(0.09733285267845754)),
 (263, np.float64(0.09733285267845754)),
 (878, np.float64(0.09733285267845754)),
 (1154, np.float64(0.09733285267845754)),
 (1723, np.float64(0.09733285267845754)),
 (1938, np.float64(0.09733285267845754)),
 (2783, np.float64(0.09733285267845754)),
 (4254, np.float64(0.09733285267845754)),
 (4403, np.float64(0.09733285267845754)),
 (4472, np.float64(0.09733285267845754)),
 (334, np.float64(0.0967301666813349)),
 (371, np.float64(0.09567297464698798)),
 (412, np.float64(0.09567297464698798)),
 (2237, np.float64(0.09567297464698798)),
 (2552, np.float64(0.09567297464698798)),
 (4545, np.float64(0.09558988911273408)),
 (362, np.float64(0.09544271444636668)),
 (791, np.float64(0.09544271444636668)),
 (1569, np.float64(0.09544271444636668)),
 (2558, np.float64(0.09544271444636668)),
 (4201, np.float64(0.09544271444636668)),
 (18, np.float64(0.09493290614465533)),
 (11, np.float64(0.09464970485606021)),
 (587, np.float64(0.09464970485606021)),
 (660, np.float64(0.09365858115816941)),
 (920, np.float64(0.09365858115816941)),
 (1274, np.float64(0.09365858115816941)),
 (1355, np.float64(0.09365858115816941)),
 (1470, np.float64(0.09365858115816941)),
 (1682, np.float64(0.09365858115816941)),
 (1688, np.float64(0.09365858115816941)),
 (1717, np.float64(0.09365858115816941)),
 (2392, np.float64(0.09365858115816941)),
 (2484, np.float64(0.09365858115816941)),
 (2588, np.float64(0.09365858115816941)),
 (2641, np.float64(0.09365858115816941)),
 (2646, np.float64(0.09365858115816941)),
 (2816, np.float64(0.09365858115816941)),
 (3535, np.float64(0.09365858115816941)),
 (3718, np.float64(0.09365858115816941)),
 (4331, np.float64(0.09365858115816941)),
 (4502, np.float64(0.09365858115816941)),
 (301, np.float64(0.09365858115816939)),
 (129, np.float64(0.09269795493186431)),
 (243, np.float64(0.09269795493186431)),
 (279, np.float64(0.09269795493186431)),
 (473, np.float64(0.09269795493186431)),
 (596, np.float64(0.09269795493186431)),
 (813, np.float64(0.09269795493186431)),
 (1442, np.float64(0.09269795493186431)),
 (1697, np.float64(0.09269795493186431)),
 (3405, np.float64(0.09269795493186431)),
 (785, np.float64(0.09243423333081695)),
 (219, np.float64(0.09197090092274487)),
 (244, np.float64(0.09197090092274487)),
 (511, np.float64(0.09197090092274487)),
 (978, np.float64(0.09197090092274487)),
 (1752, np.float64(0.09197090092274487)),
 (2089, np.float64(0.09197090092274487)),
 (2647, np.float64(0.09197090092274487)),
 (3734, np.float64(0.09197090092274487)),
 (230, np.float64(0.09183979479633063)),
 (799, np.float64(0.09183979479633063)),
 (239, np.float64(0.09125667909262308)),
 (2566, np.float64(0.09125667909262308)),
 (43, np.float64(0.09086217008485092)),
 (602, np.float64(0.09086217008485092)),
 (995, np.float64(0.09086217008485092)),
 (1231, np.float64(0.09086217008485092)),
 (1842, np.float64(0.09086217008485092)),
 (3879, np.float64(0.09086217008485092)),
 (12, np.float64(0.09037128496931669)),
 (88, np.float64(0.09037128496931669)),
 (167, np.float64(0.09037128496931669)),
 (356, np.float64(0.09037128496931669)),
 (400, np.float64(0.09037128496931669)),
 (1304, np.float64(0.09037128496931669)),
 (1476, np.float64(0.09037128496931669)),
 (2247, np.float64(0.09037128496931669)),
 (2864, np.float64(0.09037128496931669)),
 (2955, np.float64(0.09037128496931669)),
 (331, np.float64(0.08998425413316952)),
 (2359, np.float64(0.08998425413316952)),
 (2792, np.float64(0.08998425413316952)),
 (2852, np.float64(0.08998425413316952)),
 (3387, np.float64(0.08998425413316952)),
 (3441, np.float64(0.08998425413316952)),
 (3460, np.float64(0.08998425413316952)),
 (4343, np.float64(0.08998425413316952)),
 (4353, np.float64(0.08998425413316952)),
 (274, np.float64(0.08977310580745099)),
 (1902, np.float64(0.0891313035643173)),
 (2111, np.float64(0.08903057122447033)),
 (292, np.float64(0.08885233166386385)),
 (564, np.float64(0.08885233166386385)),
 (1025, np.float64(0.08885233166386385)),
 (2656, np.float64(0.08885233166386385)),
 (3320, np.float64(0.08885233166386385)),
 (169, np.float64(0.08830215713766959)),
 (270, np.float64(0.08830215713766959)),
 (618, np.float64(0.08830215713766959)),
 (1779, np.float64(0.08830215713766959)),
 (2105, np.float64(0.08830215713766959)),
 (2709, np.float64(0.08830215713766959)),
 (2736, np.float64(0.08830215713766959)),
 (3551, np.float64(0.08830215713766959)),
 (479, np.float64(0.08797691788472335)),
 (752, np.float64(0.08749572785196143)),
 (1828, np.float64(0.08749572785196143)),
 (2444, np.float64(0.08746392856766495)),
 (23, np.float64(0.08740748201220976)),
 (141, np.float64(0.08740748201220976)),
 (389, np.float64(0.08740748201220976)),
 (745, np.float64(0.08740748201220976)),
 (794, np.float64(0.08740748201220976)),
 (960, np.float64(0.08740748201220976)),
 (1247, np.float64(0.08740748201220976)),
 (1257, np.float64(0.08740748201220976)),
 (3446, np.float64(0.08740748201220976)),
 (3447, np.float64(0.08740748201220976)),
 (143, np.float64(0.08671099695241201)),
 (199, np.float64(0.08671099695241201)),
 (827, np.float64(0.08671099695241201)),
 (1526, np.float64(0.08671099695241201)),
 (2876, np.float64(0.08671099695241201)),
 (3554, np.float64(0.08671099695241201)),
 (4516, np.float64(0.08671099695241201)),

In [61]:
def recommend(movie):
  mov_in=new_df[new_df['title']==movie].index[0]
  dist=s[mov_in]
  mov_list=sorted(list(enumerate(dist)),reverse=True,key=lambda x:x[1])[1:6]

  for i in mov_list:
    print(new_df.iloc[i[0]].title)

In [62]:
recommend('Avatar')

Aliens vs Predator: Requiem
Aliens
Falcon Rising
Independence Day
Titan A.E.

In [63]:
import pickle

In [64]:
pickle.dump(new_df, open('movies.pkl', 'wb'))

In [65]:
#from google.colab import files

#files.download('movies.pkl')

In [66]:
pickle.dump(new_df.to_dict(), open('movies_dict.pkl', 'wb'))

In [67]:
#from google.colab import files

#files.download('movies_dict.pkl')

In [68]:
pickle.dump(s, open('similarity.pkl', 'wb'))

In [69]:
#from google.colab import files

#files.download('similarity.pkl')